// 전역 데이터 (전부 정상 문법으로 수정 완료)
const STORE_DATA = [
  { category: "분식", name: "명가떡볶이", sub: "떡볶이, 김밥", price: "1만원 이하" },
  { category: "분식", name: "참새방앗간", sub: "즉석 떡볶이", price: "1만원 이하" },
  { category: "분식", name: "셀분식", sub: "종합분식", price: "1만원 이하" },
  { category: "분식", name: "신전떡볶이", sub: "떡볶이, 김밥", price: "1만원 이하" },

  { category: "간편식", name: "도스마스", sub: "부리또", price: "1만원 이하" },
  { category: "간편식", name: "밀플랜비", sub: "부리또", price: "1만원 이하" },
  { category: "간편식", name: "행컵", sub: "컵밥", price: "1만원 이하" },
  { category: "간편식", name: "한솥도시락", sub: "도시락", price: "1만원 이하" },
  { category: "간편식", name: "정직유부", sub: "유부초밥", price: "1만원 이하" },
  { category: "간편식", name: "봉구스밥버거", sub: "밥버거, 컵밥", price: "1만원 이하" },
  { category: "간편식", name: "이삭토스트", sub: "토스트", price: "1만원 이하" },
  { category: "간편식", name: "서브웨이", sub: "샌드위치", price: "2만원 이하" },
  { category: "간편식", name: "올리브샌드위치", sub: "샌드위치", price: "1만원 이하" },

  { category: "야식", name: "더치킨", sub: "치킨", price: "2만원 이하" },
  { category: "야식", name: "미쳐버린파닭", sub: "치킨", price: "2만원 이하" },
  { category: "야식", name: "대학통닭", sub: "치킨", price: "2만원 이하" },
  { category: "야식", name: "계림원", sub: "치킨", price: "3만원 이하" },

  { category: "동남아", name: "인더비엣", sub: "쌀국수, 볶음밥", price: "2만원 이하" },
  { category: "동남아", name: "남월", sub: "쌀국수, 볶음밥", price: "1만원 이하" },
  { category: "동남아", name: "자이카", sub: "카레", price: "1만원 이하" },
  { category: "동남아", name: "카바레식당", sub: "카레, 크림우동", price: "2만원 이하" },

  { category: "일식", name: "유메", sub: "라멘", price: "1만원 이하" },
  { category: "일식", name: "오벤라멘", sub: "라멘", price: "1만원 이하" },
  { category: "일식", name: "백소정", sub: "돈가츠", price: "2만원 이하" },
  { category: "일식", name: "코운즈", sub: "라멘, 돈가츠", price: "2만원 이하" },
  { category: "일식", name: "면식당", sub: "라멘, 돈가츠", price: "2만원 이하" },
  { category: "일식", name: "에비수", sub: "롤, 덮밥", price: "2만원 이하" },
  { category: "일식", name: "한그릇", sub: "덮밥", price: "2만원 이하" },
  { category: "일식", name: "핵밥", sub: "덮밥", price: "2만원 이하" },

  { category: "중식", name: "북경반점", sub: "짜장면, 짬뽕", price: "1만원 이하" },
  { category: "중식", name: "도야짬뽕", sub: "짜장면, 짬뽕", price: "2만원 이하" },
  { category: "중식", name: "전국5대짬뽕 교동짬뽕", sub: "짜장면, 짬뽕", price: "1만원 이하" },
  { category: "중식", name: "찐하오마라탕", sub: "마라탕", price: "1800/100g" },
  { category: "중식", name: "라화쿵푸", sub: "마라탕", price: "1850/100g" },
  { category: "중식", name: "홍성마라미방", sub: "마라탕", price: "1800/100g" },
  { category: "중식", name: "산시도삭면", sub: "딤섬, 도삭면", price: "1만원 이하" },
  { category: "중식", name: "대홍훠거샤브샤브", sub: "훠궈", price: "3만원 이하" },

  { category: "양식", name: "양식당", sub: "파스타", price: "2만원 이하" },
  { category: "양식", name: "토핑온피테스", sub: "버거", price: "1만원 이하" },
  { category: "양식", name: "엔의식탁", sub: "파스타", price: "2만원 이하" },
  { category: "양식", name: "성북동경양식", sub: "커틀릿", price: "2만원 이하" },
  { category: "양식", name: "브라운돈까스", sub: "커틀릿", price: "2만원 이하" },
  { category: "양식", name: "은화수식당", sub: "커틀릿", price: "2만원 이하" },
  { category: "양식", name: "언니네화덕피자", sub: "피자, 파스타", price: "2만원 이하" },
  { category: "양식", name: "피자스쿨", sub: "피자", price: "1만원 이하" },
  { category: "양식", name: "버텍스", sub: "미국식 덮밥", price: "2만원 이하" },
  { category: "양식", name: "페퍼로니네트", sub: "피자", price: "3만원 이하" },

  { category: "한식", name: "예삿닭갈비감자탕", sub: "닭갈비, 감자탕", price: "3만원 이하" },
  { category: "한식", name: "유가네닭갈비", sub: "닭갈비", price: "2만원 이하" },
  { category: "한식", name: "오무라이스", sub: "덮밥", price: "1만원 이하" },
  { category: "한식", name: "교반옥식비빔밥", sub: "비빔밥", price: "1만원 이하" },
  { category: "한식", name: "홍익돈까스", sub: "돈까스", price: "1만원 이하" },
  { category: "한식", name: "산들에한상", sub: "백반", price: "1만원 이하" },
  { category: "한식", name: "가전고기", sub: "돼지고기", price: "2만원 이하" },

  { category: "술집", name: "역전할머니맥주", sub: "맥주, 호프", price: "2만원 이하" },
  { category: "술집", name: "만취", sub: "요리주점", price: "2만원 이하" },
  { category: "술집", name: "A+", sub: "요리주점", price: "2만원 이하" },
  { category: "술집", name: "더솥", sub: "요리주점", price: "2만원 이하" },
  { category: "술집", name: "로드락비어", sub: "맥주, 호프", price: "2만원 이하" },
  { category: "술집", name: "밤새", sub: "막걸리", price: "2만원 이하" },
  { category: "술집", name: "락(樂)", sub: "요리주점", price: "2만원 이하" },
   { category: "술집", name: "달달포차", sub: "포장마차", price: "2만원 이하" },

];
